name: 📜 Draft a release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "New version to draft release"
        required: true
        type: string

jobs:
  release:
    name: Draft a Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Define version
        run: |
          INPUT_VERSION=${{ github.event.inputs.version }}
          NEW_VERSION=${INPUT_VERSION:-"0.0.1"} 
          echo "Input version: ${INPUT_VERSION}"
          echo "New version: ${NEW_VERSION}"
          echo "NEW_VERSION=${NEW_VERSION}" >> $GITHUB_ENV

      - name: Version validation
        run: |
          if ! echo "$NEW_VERSION" | grep -Eq '^[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?(\+[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?$'; then
            echo "Invalid semver format" >&2
            exit 1
          fi

      - name: Get latest tag
        id: latest-tag
        run: |
          git fetch --tags
          LATEST_TAG=$(git tag | tail -n1)
          echo "latest_tag=${LATEST_TAG}" >> $GITHUB_OUTPUT

      - name: Version comparison
        id: compare-versions
        run: |
          LATEST_VERSION="${{ steps.latest-tag.outputs.latest_tag }}"
          echo "Latest version: $LATEST_VERSION"
          echo "New version: $NEW_VERSION"

          if dpkg --compare-versions $NEW_VERSION le $LATEST_VERSION; then
            echo "New version must be higher than $LATEST_VERSION"
            exit 1
          fi

      - name: Version bump
        id: version-bump
        run: |
          npm --no-git-tag-version version "$NEW_VERSION"
          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Version commit
        uses: EndBug/add-and-commit@v9
        with:
          add: "package.json"
          default_author: github_actor
          message: "feat(repo): ${{ steps.version-bump.outputs.version }}"
          push: true

      - name: Create release draft
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          name: ${{ steps.version-bump.outputs.version }}
          tag_name: ${{ steps.version-bump.outputs.version }}
