name: "⚒️ issue"

on:
  push:
    branches:
      - issue/**

    paths:
      - ".github/workflows/issue.yml"
      - "src/**"
      - "husky-hooks.config.default.js"
      - "package.json"
      - "tsconfig.json"
      - "yarn.lock"

env:
  NODE_ENV: "development"
  RUNTIME_ENV: "main"

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    timeout-minutes: 15

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install depencencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Test
        run: |

          # Remove current config
          rm husky-hooks.config.js

          # Test create-config
          npx @jeliasson/husky-hooks pre-commit

          # Test create-config with --force
          npx @jeliasson/husky-hooks pre-commit --force

          # Update protectedBranches to be []
          cp husky-hooks.config.js husky-hooks.config.js.bak && \
          cat husky-hooks.config.js.bak | sed 's/.*protectedBranches.*/\      protectedBranches = []/' > husky-hooks.config.js

          # Test hooks
          npx @jeliasson/husky-hooks pre-commit
          npx @jeliasson/husky-hooks pre-push
